#!/usr/bin/env python3
"""Local document-properties QA for FastXLSX generated workbooks.

This helper is intentionally outside CTest. It verifies `docProps/core.xml` and
`docProps/app.xml` directly, then uses openpyxl only as a local QA reader for
core workbook properties. Python XLSX libraries are not FastXLSX runtime
dependencies.
"""

from __future__ import annotations

import argparse
import json
import sys
import zipfile
from pathlib import Path
from typing import Any


EXPECTED = {
    "in_memory": {
        "sheet": "Props",
        "a1": "doc props",
        "creator": "Alice & Bob",
        "last_modified_by": "QA <Owner>",
        "title": "Quarterly <Report>",
        "subject": "Metadata & API",
        "description": "Generated by FastXLSX <test>",
        "keywords": "xlsx;docprops",
        "category": "Validation",
        "application": "FastXLSX Unit & Tools",
        "app_version": "2.5",
        "escaped": {
            "creator": "<dc:creator>Alice &amp; Bob</dc:creator>",
            "last_modified_by": "<cp:lastModifiedBy>QA &lt;Owner&gt;</cp:lastModifiedBy>",
            "title": "<dc:title>Quarterly &lt;Report&gt;</dc:title>",
            "subject": "<dc:subject>Metadata &amp; API</dc:subject>",
            "description": (
                "<dc:description>Generated by FastXLSX &lt;test&gt;</dc:description>"
            ),
            "application": "<Application>FastXLSX Unit &amp; Tools</Application>",
        },
    },
    "streaming": {
        "sheet": "StreamProps",
        "a1": "document properties",
        "creator": "Stream & Author",
        "last_modified_by": "Stream <QA>",
        "title": "Streaming <Props>",
        "subject": "DocProps & Streaming",
        "description": "Streaming docProps test",
        "keywords": "streaming;docprops",
        "category": "Validation",
        "application": "FastXLSX Streaming & Tools",
        "app_version": "3.1",
        "escaped": {
            "creator": "<dc:creator>Stream &amp; Author</dc:creator>",
            "last_modified_by": "<cp:lastModifiedBy>Stream &lt;QA&gt;</cp:lastModifiedBy>",
            "title": "<dc:title>Streaming &lt;Props&gt;</dc:title>",
            "subject": "<dc:subject>DocProps &amp; Streaming</dc:subject>",
            "description": "<dc:description>Streaming docProps test</dc:description>",
            "application": "<Application>FastXLSX Streaming &amp; Tools</Application>",
        },
    },
}


def require(condition: bool, message: str) -> None:
    if not condition:
        raise AssertionError(message)


def read_zip_text(path: Path, name: str) -> str:
    with zipfile.ZipFile(path) as archive:
        with archive.open(name) as entry:
            return entry.read().decode("utf-8")


def zip_names(path: Path) -> set[str]:
    with zipfile.ZipFile(path) as archive:
        return set(archive.namelist())


def verify_package(path: Path, scenario: str) -> dict[str, Any]:
    expected = EXPECTED[scenario]
    names = zip_names(path)
    required = [
        "[Content_Types].xml",
        "_rels/.rels",
        "docProps/core.xml",
        "docProps/app.xml",
        "xl/workbook.xml",
        "xl/_rels/workbook.xml.rels",
        "xl/worksheets/sheet1.xml",
    ]
    for name in required:
        require(name in names, f"{scenario}: missing package entry: {name}")
    require("docProps/custom.xml" not in names,
            f"{scenario}: document properties API should not create docProps/custom.xml")

    content_types = read_zip_text(path, "[Content_Types].xml")
    require("/docProps/core.xml" in content_types,
            f"{scenario}: missing core properties content type override")
    require("/docProps/app.xml" in content_types,
            f"{scenario}: missing app properties content type override")
    require("/docProps/custom.xml" not in content_types,
            f"{scenario}: unexpected custom properties content type")

    package_rels = read_zip_text(path, "_rels/.rels")
    require('Target="docProps/core.xml"' in package_rels,
            f"{scenario}: missing core properties relationship")
    require('Target="docProps/app.xml"' in package_rels,
            f"{scenario}: missing app properties relationship")
    require("docProps/custom.xml" not in package_rels,
            f"{scenario}: unexpected custom properties relationship")

    core_xml = read_zip_text(path, "docProps/core.xml")
    for key, fragment in expected["escaped"].items():
        if key == "application":
            continue
        require(fragment in core_xml, f"{scenario}: missing escaped core property {key}")
    require(f"<cp:keywords>{expected['keywords']}</cp:keywords>" in core_xml,
            f"{scenario}: keywords mismatch")
    require(f"<cp:category>{expected['category']}</cp:category>" in core_xml,
            f"{scenario}: category mismatch")

    app_xml = read_zip_text(path, "docProps/app.xml")
    require(expected["escaped"]["application"] in app_xml,
            f"{scenario}: application escaping mismatch")
    require(f"<AppVersion>{expected['app_version']}</AppVersion>" in app_xml,
            f"{scenario}: app version mismatch")

    return {
        "verified_entries": required,
        "custom_properties_absent": True,
        "core_properties": {
            key: expected[key]
            for key in [
                "creator",
                "last_modified_by",
                "title",
                "subject",
                "description",
                "keywords",
                "category",
            ]
        },
        "app_properties": {
            "application": expected["application"],
            "app_version": expected["app_version"],
        },
    }


def verify_with_openpyxl(path: Path, scenario: str) -> dict[str, Any]:
    try:
        import openpyxl  # type: ignore
    except ModuleNotFoundError as exc:
        raise RuntimeError("openpyxl is required for this local QA helper") from exc

    expected = EXPECTED[scenario]
    workbook = openpyxl.load_workbook(path, read_only=False, data_only=False)
    try:
        require(expected["sheet"] in workbook.sheetnames,
                f"{scenario}: missing worksheet {expected['sheet']}")
        worksheet = workbook[expected["sheet"]]
        require(worksheet["A1"].value == expected["a1"],
                f"{scenario}: A1 smoke value mismatch: {worksheet['A1'].value!r}")
        props = workbook.properties
        checks = {
            "creator": props.creator,
            "last_modified_by": props.lastModifiedBy,
            "title": props.title,
            "subject": props.subject,
            "description": props.description,
            "keywords": props.keywords,
            "category": props.category,
        }
        for key, observed in checks.items():
            require(observed == expected[key],
                    f"{scenario}: openpyxl {key} mismatch: {observed!r}")
        return {
            "status": "opened",
            "sheetnames": workbook.sheetnames,
            "sheet": expected["sheet"],
            "a1": worksheet["A1"].value,
            "core_properties": checks,
            "app_properties_note": (
                "Application and AppVersion are verified from docProps/app.xml; "
                "openpyxl is not the authority for extended app properties."
            ),
        }
    finally:
        workbook.close()


def verify_workbook(path: Path, scenario: str) -> dict[str, Any]:
    return {
        "input": str(path),
        "package": verify_package(path, scenario),
        "openpyxl": verify_with_openpyxl(path, scenario),
    }


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--in-memory-input",
        type=Path,
        default=Path("build/windows-nmake-release/tests/fastxlsx-document-properties.xlsx"),
        help="FastXLSX in-memory document properties workbook.",
    )
    parser.add_argument(
        "--streaming-input",
        type=Path,
        default=Path("build/windows-nmake-release/tests/fastxlsx-streaming-document-properties.xlsx"),
        help="FastXLSX streaming document properties workbook.",
    )
    parser.add_argument(
        "--work-dir",
        type=Path,
        default=Path("build/qa/document-properties"),
        help="Directory for the JSON report.",
    )
    args = parser.parse_args()

    in_memory_path = args.in_memory_input.resolve()
    streaming_path = args.streaming_input.resolve()
    work_dir = args.work_dir.resolve()
    require(in_memory_path.exists(), f"in-memory workbook does not exist: {in_memory_path}")
    require(streaming_path.exists(), f"streaming workbook does not exist: {streaming_path}")
    work_dir.mkdir(parents=True, exist_ok=True)

    report = {
        "in_memory": verify_workbook(in_memory_path, "in_memory"),
        "streaming": verify_workbook(streaming_path, "streaming"),
        "comparison_scope": (
            "Core/app document properties for new workbooks only; custom "
            "properties, timestamps, existing-file editing, and full Excel UI "
            "parity are intentionally not claimed."
        ),
    }
    report_path = work_dir / "report.json"
    report_path.write_text(json.dumps(report, indent=2, ensure_ascii=False), encoding="utf-8")
    print(json.dumps(report, indent=2, ensure_ascii=False))
    return 0


if __name__ == "__main__":
    try:
        raise SystemExit(main())
    except Exception as exc:  # pragma: no cover - local QA helper
        print(f"ERROR: {exc}", file=sys.stderr)
        raise SystemExit(1)
