#pragma once

#include "package_reader.hpp"
#include "package_writer.hpp"

#include <fastxlsx/detail/worksheet_transformer.hpp>
#include <fastxlsx/document_properties.hpp>

#include <cstddef>
#include <filesystem>
#include <span>
#include <string>
#include <string_view>
#include <vector>

namespace fastxlsx::detail {

// Current internal sheetData patch helper materializes the planned worksheet XML.
// Keep that path bounded until a true streaming worksheet transformer exists.
inline constexpr std::size_t package_editor_sheet_data_local_rewrite_byte_limit =
    4U * 1024U * 1024U;

// Current cell replacement uses this as the event-reader retained-window guard.
// Source package worksheet entries, planned staged chunks, and queued planned
// strings are scanned through chunk-source readers; queued strings may already
// have been materialized by the prior planned replacement helper.
inline constexpr std::size_t package_editor_cell_replacement_materialized_input_byte_limit =
    4U * 1024U * 1024U;

struct PackagePartReplacement {
    PartName part_name;
    std::string data;
    std::vector<PackageEntryChunk> chunks;
    PartWriteMode write_mode = PartWriteMode::LocalDomRewrite;
    std::string reason;
};

struct PackageEntryReplacement {
    std::string entry_name;
    std::string data;
};

struct PackageEditorOutputEntryPlan {
    std::string entry_name;
    PartWriteMode write_mode = PartWriteMode::CopyOriginal;
    bool source_entry = false;
    bool package_part = false;
    bool generated = false;
    bool copied_from_source = false;
    bool omitted = false;
    PackageEntryAuditKind audit_kind = PackageEntryAuditKind::Generic;
    std::string part_name;
    std::string owner_part;
    std::string relationship_owner_part;
    std::string relationship_id;
    std::string relationship_type;
    std::string relationship_target;
    std::vector<RemovedPartInboundRelationshipAudit> inbound_relationships;
    std::string reason;
};

struct PackageEditorOutputPlan {
    std::vector<PackageEditorOutputEntryPlan> entries;
    bool full_calculation_on_load = false;
    CalcChainAction calc_chain_action = CalcChainAction::Preserve;
    std::vector<std::string> notes;
    std::vector<EditPlanRemovedPart> removed_parts;
    std::vector<EditPlanRemovedPackageEntry> removed_package_entries;
    std::vector<RelationshipTargetAudit> relationship_target_audits;
    std::vector<WorksheetRelationshipReferenceAudit> worksheet_relationship_reference_audits;
    std::vector<WorksheetPayloadDependencyAudit> worksheet_payload_dependency_audits;
    std::vector<WorkbookPayloadDependencyAudit> workbook_payload_dependency_audits;
};

// Internal PackageEditor foundation for the Patch path.
//
// This first slice opens an existing stored/no-compression package through
// PackageReader, records part-level replacement intent and metadata-entry audit
// in an EditPlan, and writes a new package by copying untouched entry bytes.
// Ordinary part replacement rejects OPC metadata package entries such as
// `[Content_Types].xml` and `.rels`; those entries are only changed by the
// narrow metadata-aware helpers that also update the package-entry audit.
// If an ordinary part replacement targets a part previously generated by a
// metadata-aware helper, the ordinary replacement becomes the final part bytes
// while metadata entries such as content types and package relationships keep
// their helper-managed audit. If a metadata-aware helper later takes ownership
// of a previously ordinary-replaced part, the helper output becomes final and
// stale ordinary replacement state is discarded. The core/app docProps helper
// can also take ownership after explicit removal by restoring generated payload
// output; it does not restore source-owned docProps `.rels` entries.
// A later ordinary replacement can also restore a previously removed source
// package part as the active final state, clearing the stale removal/omission
// audit, reusing any source-owned `.rels` entry as copy-original metadata, and
// returning content types to source/copy-original state when the restored part
// brings back the source override.
// Worksheet replacement can update the small workbook/content-type/relationship
// metadata needed for the conservative calcChain-remove/fullCalcOnLoad policy,
// while untouched source worksheet relationships and linked object parts are
// copied as-is. Preserved source-owned `.rels` entries can also be recorded as
// copy-original package-entry audit metadata in the EditPlan with structured
// source-owner context, including workbook `.rels` when workbook metadata
// changes but relationships do not. If ordinary workbook replacement follows a
// worksheet rewrite that requested recalculation, the replacement workbook XML
// is kept consistent with the existing fullCalcOnLoad / calcChain plan and does
// not downgrade already-rewritten workbook `.rels` audit metadata.
// Worksheet replacement also performs audit-only checks between relationship
// ids referenced by replacement worksheet XML and the preserved worksheet
// `.rels` entry. Missing ids, stale unreferenced ids, and known worksheet
// element/type mismatches are reported as notes and structured
// WorksheetRelationshipReferenceAudit records under the default preserve policy.
// `ReferencePolicyAction::Fail` rejects those mismatches before Patch state
// changes. It also rejects worksheet replacement payload dependencies that are
// currently audit-only, such as shared string indexes, style ids, formulas, and
// worksheet-local reference/object metadata. The sheetData helper applies that
// payload guard only to the replacement <sheetData> payload itself so preserved
// wrapper metadata is not over-blocked. This slice does not validate namespaces,
// repair, prune, or regenerate worksheet relationships.
// Removed parts also omit their source-owned `.rels` entry in this narrow path
// so the output does not keep relationships for an absent owner part. Explicit
// removal is limited to source package entries and rewrites content types only
// when the removed part had an override; inbound relationships from other parts
// are audited and left untouched under the default policy. Opt-in
// `ReferencePolicyAction::Fail` rejects removals with known inbound
// relationships before Patch state changes. This
// slice rejects saving over the source package because the reader-backed
// copy path is not an atomic in-place editor. It
// is not a public editing API, Zip64 support, relationship pruning/orphan
// cleanup, broad object preservation proof, or a full relationship/content-type
// mutator.
class PackageEditor {
public:
    [[nodiscard]] static PackageEditor open(std::filesystem::path path);
    ~PackageEditor();

    PackageEditor(const PackageEditor&) = delete;
    PackageEditor& operator=(const PackageEditor&) = delete;
    PackageEditor(PackageEditor&& other);
    PackageEditor& operator=(PackageEditor&& other);

    [[nodiscard]] const PackageReader& reader() const noexcept;
    [[nodiscard]] const PackageManifest& manifest() const noexcept;
    [[nodiscard]] const EditPlan& edit_plan() const noexcept;

    void replace_part(PartName part_name, std::string data, PartWriteMode write_mode,
        std::string reason = {});
    // Internal staged package-entry source foundation for future worksheet stream
    // rewrite work. The caller supplies already-produced chunks for an existing
    // package part; this records a StreamRewrite part replacement and lets
    // save_as() hand the chunks to PackageWriter without flattening them into one
    // string. It is not a public Patch API, XML validator, dependency repair, or
    // calc metadata helper.
    void replace_part_chunks(
        PartName part_name, std::vector<PackageEntryChunk> chunks, std::string reason = {});
    void remove_part(PartName part_name, std::string reason = {},
        const ReferencePolicy& policy = {});
    void replace_worksheet_part(PartName worksheet_part, std::string worksheet_xml,
        const ReferencePolicy& policy = {});
    // Internal staged-output variant for worksheet replacement. It uses the
    // materialized worksheet_xml for current validation, dependency audit, and
    // calc metadata handling, then records the final worksheet part payload as
    // PackageEntry chunks for save_as(). This is a bridge toward package-entry
    // staged stream output, not a low-memory worksheet transformer.
    void replace_worksheet_part_chunks(PartName worksheet_part, std::string worksheet_xml,
        std::vector<PackageEntryChunk> chunks, const ReferencePolicy& policy = {});
    // Internal Patch convenience for workbook-targeted worksheet replacement.
    // Resolves the sheet name through the source workbook sheet catalog, or
    // through the currently planned `/xl/workbook.xml` bytes when an ordinary
    // workbook replacement is queued, and workbook relationships, then delegates
    // to replace_worksheet_part(). It can target a sheet name that exists only
    // in the planned workbook catalog. If `/xl/workbook.xml` has already been
    // removed from the planned package, it fails instead of falling back to the
    // source workbook catalog. It does not rename, add, delete, or repair sheets.
    void replace_worksheet_part_by_name(std::string_view sheet_name,
        std::string worksheet_xml, const ReferencePolicy& policy = {});
    // Internal Patch helper for template-style data updates. Replaces only the
    // worksheet <sheetData> element while preserving the surrounding worksheet
    // XML through a bounded local rewrite, then delegates calcChain/fullCalcOnLoad
    // and preservation handling to replace_worksheet_part(). The current helper
    // materializes the planned worksheet XML and refuses worksheets or replacement
    // payloads above package_editor_sheet_data_local_rewrite_byte_limit; it is not
    // the future large-file streaming worksheet transformer. Preserved
    // worksheet-local metadata such as
    // sheet properties, dimensions, views, default formatting, columns,
    // protection, filters, validations, print/page setup, header/footer,
    // breaks, phonetic metadata, ignored errors, drawings, worksheet object
    // references, extensions, and table references is recorded as audit notes
    // for caller review, but not repaired. It is not random cell editing or
    // semantic sync for sharedStrings, styles, tables, drawings, filters,
    // columns, print/page setup, protection, ignored errors, object
    // relationships, extensions, or merged ranges.
    void replace_worksheet_sheet_data(PartName worksheet_part, std::string sheet_data_xml,
        const ReferencePolicy& policy = {});
    // Internal Patch convenience for workbook-targeted template fills. Resolves
    // the sheet name through the source workbook sheet catalog, or through the
    // currently planned `/xl/workbook.xml` bytes when an ordinary workbook
    // replacement is queued, and workbook relationships, then delegates to
    // replace_worksheet_sheet_data(). It can target a sheet name that exists
    // only in the planned workbook catalog. If `/xl/workbook.xml` has already
    // been removed from the planned package, it fails instead of falling back to
    // the source workbook catalog. It does not rename, add, delete, or repair
    // sheets.
    void replace_worksheet_sheet_data_by_name(std::string_view sheet_name,
        std::string sheet_data_xml, const ReferencePolicy& policy = {});
    // Internal handoff from the P8 worksheet transformer foundation. Source
    // package entries are scanned through PackageReader ZIP-entry chunk sources
    // for root validation, dependency/dimension analysis, relationship-id audit,
    // and the output pass. Stored entries stream directly from the source ZIP
    // payload; DEFLATE entries still fall back to the current materialized
    // PackageReader read path.
    // Planned staged package-entry chunks are also scanned through chunk-source
    // readers. Ordinary queued/planned worksheet replacement strings are
    // scanned through a string-view chunk-source reader; the prior helper may
    // already have materialized that queued string, so this is not a fully
    // low-memory planned-input pipeline.
    // The rewritten output is streamed into a PackageEditor-owned temporary file
    // chunk instead of materializing the rewritten worksheet string. It is still
    // not a public Patch API, relationship repair, sharedStrings/style
    // migration, or a fully low-memory planned-input pipeline.
    void replace_worksheet_cells(PartName worksheet_part,
        std::span<const WorksheetCellReplacement> replacements,
        const ReferencePolicy& policy = {});
    // Internal by-name convenience for replace_worksheet_cells(); it reuses the
    // same source/planned workbook catalog resolver as the other by-name Patch
    // helpers and does not add, delete, rename, or repair sheets.
    void replace_worksheet_cells_by_name(std::string_view sheet_name,
        std::span<const WorksheetCellReplacement> replacements,
        const ReferencePolicy& policy = {});
    // Internal Patch helper for the workbook sheet catalog. Rewrites only the
    // direct `<sheets><sheet name="...">` attribute in `/xl/workbook.xml` while
    // preserving worksheet parts, workbook relationships, content types, and
    // unknown entries. It does not update defined names, formulas, tables,
    // drawings, charts, hyperlinks, or relationship targets, so callers must
    // treat it as a narrow catalog-name mutation rather than full sheet rename.
    // New-name duplicate checks are conservative and ASCII case-insensitive.
    void rename_sheet_catalog_entry(std::string_view old_name, std::string new_name,
        const ReferencePolicy& policy = {});
    // Internal small-part Patch helper. Rewrites workbook calc metadata only,
    // optionally omitting stale calcChain payload/metadata, and leaves worksheet
    // parts and linked objects copy-original.
    void request_full_calculation(
        CalcChainAction calc_chain_action = CalcChainAction::Remove);
    void set_document_properties(const DocumentProperties& properties);
    [[nodiscard]] PackageEditorOutputPlan planned_output() const;
    [[nodiscard]] std::vector<PackageEditorOutputEntryPlan> planned_output_entries()
        const;
    void save_as(const std::filesystem::path& path,
        PackageWriterOptions options = {PackageWriterBackend::StoredZipBootstrap}) const;

private:
    explicit PackageEditor(PackageReader reader);
    void replace_worksheet_part_impl(PartName worksheet_part, std::string worksheet_xml,
        const ReferencePolicy& policy, bool enforce_payload_policy);
    void replace_worksheet_part_prevalidated_chunks(PartName worksheet_part,
        std::vector<PackageEntryChunk> chunks, const ReferencePolicy& policy,
        std::vector<std::string> payload_notes,
        std::vector<WorksheetPayloadDependencyAudit> payload_audits,
        std::vector<std::string> relationship_reference_notes,
        std::vector<WorksheetRelationshipReferenceAudit> relationship_reference_audits,
        std::string replacement_reason);

    PackageReader reader_;
    PackageManifest manifest_;
    EditPlan edit_plan_;
    std::vector<PackagePartReplacement> replacements_;
    std::vector<PackageEntryReplacement> entry_replacements_;
    std::vector<std::string> omitted_entries_;
    std::vector<std::filesystem::path> temporary_files_;
};

} // namespace fastxlsx::detail
